### ISSUE TITLE
Fail if output_directory is '.'

### ISSUE THREAD

**Issue by gvanrossum** [edreamleo/make-stub-files#1]
I just get the error message `not found:` (without anything following). This seems because os.path.exists('') is false, and this is because dir_ is empty. That in turn is because normpath('./foo') returns 'foo', and then dirname() returns ''.

So the fix is to add "or not dir_" to line 1180.

**Comment by edreamleo** [comment]
Fixed at 8aaf628b. I attempted to make other parts of the code more robust and regular, but these kinds of file-name-related issues are extremely error prone.  Please reopen if other similar issues are found.
