### ISSUE TITLE
Creates duplicate annotations for function arguments that are already annotated

### ISSUE THREAD

**Issue by software-opal** [edreamleo/make-stub-files#3]
Input:
```python
class UnsupportedAlgorithm(Exception):
    def __init__(self, message: Any, reason: Optional[str]=None) -> None:
```

Output:
```python
class UnsupportedAlgorithm(Exception):
    def __init__(self, message: Any: Any, reason: Optional[str]: Any=None) -> None: ...
```

Expected output:
```python
class UnsupportedAlgorithm(Exception):
    def __init__(self, message: Any, reason: Optional[str]=None) -> None: ...
```

**Comment by edreamleo** [comment]
On Thu, Jul 5, 2018 at 11:41 PM, Lee Symes <notifications@github.com> wrote:

> Input:
>
> class UnsupportedAlgorithm(Exception):
>     def __init__(self, message: Any, reason: Optional[str]=None) -> None:
>
> Output:
>
> class UnsupportedAlgorithm(Exception):
>     def __init__(self, message: Any: Any, reason: Optional[str]: Any=None) -> None: ...
>
> Expected output:
>
> class UnsupportedAlgorithm(Exception):
>     def __init__(self, message: Any, reason: Optional[str]=None) -> None: ...
>
>
​Thanks for this report.  It's good to know that someone is using
make-stub-files.

Edward

**Comment by edreamleo** [comment]
Fixed at 44eef3.
