### ISSUE TITLE
Crash on f string and dict comprehensions (and probably something more)

### ISSUE THREAD

**Issue by boxed** [edreamleo/make-stub-files#4]
I worked around this by changing `AstFormatter.visit` to catch the AttributeError it produces with the line `method = getattr(self, method_name)` and just return empty string.

**Comment by edreamleo** [comment]
On Mon, Oct 22, 2018 at 4:40 AM Anders Hovmöller <notifications@github.com>
wrote:

> I worked around this by changing AstFormatter.visit to catch the
> AttributeError it produces with the line method = getattr(self,
> method_name) and just return empty string.
>
Again, thanks for this report.  Please file a pull request.

Edward

**Comment by boxed** [comment]
Closing this in favor of a PR
