### ISSUE TITLE
Invalid output when nesting functions

### ISSUE THREAD

**Issue by boxed** [edreamleo/make-stub-files#5]
I fixed this by adding a `node` argument to `format_return_expressions`

**Comment by edreamleo** [comment]
On Mon, Oct 22, 2018 at 4:54 AM Anders Hovmöller <notifications@github.com>
wrote:

> I fixed this by adding a node argument to format_return_expressions
>
Thanks for this report.  Would you like to file a pull request?

Edward

**Comment by edreamleo** [comment]
On Mon, Oct 22, 2018 at 5:26 AM Edward K. Ream <edreamleo@gmail.com> wrote:

> On Mon, Oct 22, 2018 at 4:54 AM Anders Hovmöller <notifications@github.com>
> wrote:
>
>> I fixed this by adding a node argument to format_return_expressions
>>
> Thanks for this report.  Would you like to file a pull request?
>

This url, https://github.com/edreamleo/make-stub-files/issues, is acting
strangely.  Sometimes it shows issues #4 and #5, and sometimes it doesn't!

Edward

**Comment by boxed** [comment]
Yea, github is having some really bad issues. Big server outage. 

I have a fork and I tried creating a PR but... well. I'll try again tomorrow.

**Comment by boxed** [comment]
Closing this in favor of a PR
