### ISSUE TITLE
[question] producing docstring/help

### ISSUE THREAD

**Issue by giuliohome** [edreamleo/make-stub-files#7]
Thank you for sharing this repo. I'm using the script to produce a stub for pylance in python extension of visual studio code.
It works as expected but, if possible, I'd love to add the documentation to the stub.
For example currently I have
`def delete_where(server: Any, database: Any, table: Any, where_clause: Any, where_params: Any) -> None: ...` 
Is there a way to produce also the following doc string so that pylance can see it?
```
def delete_where(server: Any, database: Any, table: Any, where_clause: Any, where_params: Any) -> None:
    """Deletes records from a table.

    Args:
        server (str): the server in the conn string.
        database (str): the database in the conn string.
        where_clause (str): for example 'WHERE my_field=?': use qmark.
        database (list): the list of values for the parameters in the where clause.

    Returns:
        None.
    """
```
I could manually add it in the *.pyi but then I guess I would lose it when I want to update it with a new script run, correct? Any tips? Thank you anyway.

**Edit**

Another quick question:
is there a way to make it accept a `.pyx` file as a normal python input instead of having to rename it as `.py` all the times I want to regenerate the stub?

**Comment by edreamleo** [comment]
On Sun, Feb 14, 2021 at 9:43 AM giuliohome <notifications@github.com> wrote:

> Thank you for sharing this repo.
>
You're welcome. I'm glad it has been useful.

> Is there a way to produce also the following doc string so that pylance
> can see it?
>
There's always a way :-) I don't recall much about the code, but I suspect
you are asking for a new feature. I'll take a look in a few days...

Edward
-----------------------------------------------------------------
Edward K. Ream: edreamleo@gmail.com
An old man, crazy about computer programming.
Leo Editor: http://leoeditor.com/
-----------------------------------------------------------------

**Comment by giuliohome** [comment]
No worries, solved in another way, thanks.

**Comment by edreamleo** [comment]
On Thu, Feb 18, 2021 at 5:55 AM giuliohome <notifications@github.com> wrote:

> No worries, solved in another way, thanks.
>
Glad to hear it.

Edward
